name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: write
  pull-requests: write
  pages: write
  id-token: write

concurrency:
  group: "pages"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v5
        if: github.ref == 'refs/heads/main'

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        if: github.ref == 'refs/heads/main'
        with:
          path: "./dist"

      - name: Deploy Pages
        if: github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v4

      - uses: fastify/github-action-merge-dependabot@v3